version: '3'
services:
  gethworker:
    restart: always
    build: ./geth
    volumes:
      - gethvol:/vol
    expose:
      - "8545"
      - "8546"
  app:
    restart: always
    build: ./app
    ports:
      - "6000:13000"
    depends_on: 
      - gethworker
    volumes:
      - appvol:/vol
    env_file:
      - .env
    command: ["/app/bin/start-supervisor"]
volumes:
  gethvol: {}
  appvol: {}
